name: billapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  logging: ^1.2.0
  uuid: ^4.3.3
  share_plus: ^7.1.0
  fl_chart: ^0.66.0
  month_year_picker: ^0.5.0+1
  image_picker: ^1.1.1
  google_mlkit_text_recognition: ^0.15.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
